name: ?f"Conservative fold change estimates for the contrast of {wildcards.sample_changed}-{wildcards.unit_changed} vs. {wildcards.sample_baseline}-{wildcards.unit_baseline}."
datasets:
  gfold_table:
    path: ?input.gfold_table
    offer-excel: true
    separator: "\t"
default-view: gfold_table
views:
  gfold_table:
    dataset: gfold_table
    desc: |
        ?f"Conservative fold change estimates for the contrast of {wildcards.sample_changed}-{wildcards.unit_changed} vs. {wildcards.sample_baseline}-{wildcards.unit_baseline}."
    page-size: 25
    render-table:
      columns:
        transcript_id:
          display-mode: normal
          link-to-url: 
            Ensembl:
              url: "https://www.ensembl.org/Homo_sapiens/Transcript/Summary?t={transcript_id}"
        gene_symbol:
          display-mode: normal
          link-to-url: 
            GeneCards:
              url: "https://www.genecards.org/cgi-bin/carddisp.pl?gene={gene_symbol}"
        gfold_0_01:
          plot:
            heatmap:
              scale: linear
              range:
                - "#e6550d"
                - "white"
                - "#6baed6"
              domain:
                - -1
                - 0
                - 1
        e_fdr:
          plot:
            bars:
              scale: linear
        log2fdc:
          plot:
            bars:
              scale: linear
        rpkm_baseline:
          plot:
            bars:
              scale: linear
        rpkm_changed:
          plot:
            bars:
              scale: linear