name: ?f"Conservative fold change estimates for the contrast of {wildcards.sample_changed}-{wildcards.unit_changed} vs. {wildcards.sample_baseline}-{wildcards.unit_baseline}."
datasets:
  gfold_table:
    path: ?input.gfold_table
    offer-excel: true
    separator: "\t"
default-view: gfold_table
views:
  gfold_table:
    dataset: gfold_table
    desc: |
        ?f"Conservative fold change estimates for the contrast of {wildcards.sample_changed}-{wildcards.unit_changed} vs. {wildcards.sample_baseline}-{wildcards.unit_baseline}."
    page-size: 25
    render-table:
      columns:
        transcript_id:
          display-mode: normal
          link-to-url: 
            Ensembl:
              url: "https://www.ensembl.org/Homo_sapiens/Transcript/Summary?t={transcript_id}"
        gene_symbol:
          display-mode: normal
          link-to-url: 
            GeneCards:
              url: "https://www.genecards.org/cgi-bin/carddisp.pl?gene={gene_symbol}"
        gfold_0_01:
          custom-plot:
            data: |
              function(value, row) {
                // Generate data for this cell, having access to the value and any other values from
                // the same row.
                return [{"gfold": value}]
              }
            spec: |
              {
                "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
                "mark": {
                  "type": "rect",
                  "align": "left"
                },
                "encoding": {
                  "x": {
                    "field": "dummy",
                    "axis": {
                      "labelExpr": "gfold_0.01",
                      "labelAngle": -90,
                      "title": null,
                      "ticks": false,
                      "orient": "top",
                      "domain": false
                    }
                  },
                  "y": {
                    "field": "index",
                    "type": "ordinal",
                    "axis": null
                  },
                  "color": {
                    "field": "gfold",
                    "type": "quantitative",
                    "scale": {
                      "domainMid": 0
                    }
                  }
                },
                "mark": {
                  "type": "text",
                  "align":"left",
                  "xOffset": -6
                },
                "encoding": {
                  "text": {"field": "gfold"},
                  "y": {
                    "field": "index",
                    "type": "ordinal",
                    "axis": null
                  }
                },
                "config": {"legend": {"disable": true}}
              }
        e_fdr:
          plot:
            ticks:
              scale: linear
        log2fdc:
          plot:
            heatmap:
              type: quantitative
              scale: linear
        rpkm_baseline:
          plot:
            ticks:
              scale: linear
        rpkm_changed:
          plot:
            ticks:
              scale: linear