__use_yte__: true

name: ?f"Conservative fold change estimates for the contrast {wildcards.contrast}"

datasets:
  gfold_table:
    path: ?input.gfold_table
    separator: "\t"

default-view: gfold_table

views:
  gfold_table:
    dataset: gfold_table
    desc: |
        ?f"Conservative fold change estimates for the contrast of {wildcards.sample_changed}-{wildcards.unit_changed} vs. {wildcards.sample_baseline}-{wildcards.unit_baseline}."
    page-size: 25
    render-table:
      columns:
        transcript_id:
          display-mode: normal
          link-to-url: 
            Ensembl:
              url: "https://www.ensembl.org/Homo_sapiens/Transcript/Summary?t={transcript_id}"
        gene_id:
          display-mode: normal
          link-to-url: 
            Ensembl:
              url: "https://www.ensembl.org/Homo_sapiens/Gene/Summary?g={gene_id}"
        gene_symbol:
          display-mode: normal
          link-to-url: 
            GeneCards:
              url: "https://www.genecards.org/cgi-bin/carddisp.pl?gene={gene_symbol}"
        gfold_0_01:
          plot:
            heatmap:
              scale: linear
              range:
                - "#B2182B"
                - "#F7F7F7"
                - "#2166AC"
              domain-mid: 0
        e_fdr:
          plot:
            ticks:
              scale: linear
        log2fdc:
          plot:
            heatmap:
              scale: linear
              range:
                - "#B2182B"
                - "#F7F7F7"
                - "#2166AC"
              domain-mid: 0
        rpkm_baseline:
          plot:
            ticks:
              scale: linear
        rpkm_changed:
          plot:
            ticks:
              scale: linear